### ISSUE TITLE
pip installation failing on glibc < 2.35

### ISSUE THREAD

**Issue by maxwelllwang** [daily-co/daily-python#10]
**Could daily-python support older glibc versions or would it be possible to built from source with an older version of glibc? or statically link with musl?** 

Trying to install daily-python on my jetson nano running inside Ubuntu 18.04 bionic docker container

```
# python3.8 -V
Python 3.8.10
# uname -m
aarch64
python3.8 -m pip install daily-python
Collecting daily-python
Could not find a version that satisfies the requirement daily-python (from versions: )
No matching distribution found for daily-python
```
```
# python3.10 -m pip install daily_python-0.3.1-cp38-abi3-manylinux_2_35_aarch64.whl
ERROR: daily_python-0.3.1-cp38-abi3-manylinux_2_35_aarch64.whl is not a supported wheel on this platform.
```

It works on docker images with newer versions of glibc like debian bookworm. However to take advantage of CUDA acceleration I need to use l4t-base docker images which max out at glibc 2.31. Upgrading glibc is not a trivial process on older OSes.

Thanks!

**Comment by aconchillo** [comment]
Hi @maxwelllwang . Thank you for reporting this. Unfortunately, we only provide binaries for now, since `daily-python` depends on an internal library that is currently not publicly available, for now. However, we've seen some interest in getting `daily-python` working on older glibc versions, so I'll see what I can do.

**Comment by maxwelllwang** [comment]
Thank you! Big fan of the SDK, its working really well on newer platforms and I'm excited to get it working on older platforms. Doesn't look like this will happen overnight, will keep checking pypi project and find a workaround for now.l

**Comment by aconchillo** [comment]
> Thank you! Big fan of the SDK, its working really well on newer platforms and I'm excited to get it working on older platforms. Doesn't look like this will happen overnight, will keep checking pypi project and find a workaround for now.l

Glad to hear that! We are working on a new release but we will definitely try to have something soon. We'll keep you posted.

**Comment by aconchillo** [comment]
Hi @maxwelllwang ! I'm happy to announce that `daily-python` 0.4.0 now supports python3.7 and glibc >= 2.28. I have tried it with a Jetson Nano inside an l4t-base container following: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-base

The only special thing I had to do is install a newer version of `pip3` since the one from the `python3-pip` package is too old. I used:

```
pip3 install --upgrade pip
```

The new `pip3` will be installed in `/usr/local/bin`, so make sure that's the one you execute when you try `pip3 install daily-python`.

Let me know if you have any issues!
